# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 885ed85fed6741789f62cb6ca02532a98db0b7737046342db64b39e2860fe0587fa714d54f4910bb07d5b2de1c8b5eef24da8c65267892a8343282ab75e251e0

test:
  secret_key_base: 55721c7f9926bab7c24aac31b9038ad8e63945c7d3cf832cd0c358691217486ecb0231bd055a9bfa1009ca084068bd2710f22aaab398789af4c12f517a73c81b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
